### ISSUE TITLE
segfault when importing from tstab.so

### ISSUE THREAD

**Issue by swehrwein** [fperazzi/davis#3]
I'm trying to run this on Mac OS 10.11.6 and I get a segfault when I run the eval scripts. I traced it down to
`from tstab import *`
in line 6 of t_stability.py. Everything is building fine except for a CMake warning about MACOS_RPATH not being specified for the tstab target, which seems like it could be related. Any idea what's going wrong?

**Comment by fperazzi** [comment]
I'm not sure how to replicate your problem. I need more information. Are you trying to evaluate your own results or those provided?

**Comment by swehrwein** [comment]
I'm trying to figure out how to get more debugging information but it looks like debugging python extensions on mac using gdb or similar requires pretty involved setup. I will work on this, but to clarify: the segfault happens while the tstab module is being imported; as I understand it, this happens before any data is loaded. The segfault also happens if I simply open ipython and `import tstab`.

**Comment by swehrwein** [comment]
Okay, problem "solved" - sorry for the errant issue; I'll mention the problem and my fix for anyone else who encounters this issue.

Problem: If you have installed Python on Mac OS using homebrew alongside the system install, CMake's find_package(PythonInterp) will find homebrew's Python interpreter but find_package(PythonLibs) will find the OS's python libraries.

Fix: convince CMake to use the homebrew libraries by editing the call to `cmake` in configure.sh. Pass tell it where to look for python e.g. by passing:
`-DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython2.7.dylib -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python2.7`

For an more thorough writeup of the issue and where I found the suggested fix, see https://github.com/pybind/pybind11/issues/99.

**Comment by fperazzi** [comment]
Great, thanks a lot for posting the solution!

**Comment by shoutOutYangJie** [comment]
Hello, @swehrwein  Do you know how to use anaconda (py3.6) to support "t_stab" library?

**Comment by swehrwein** [comment]
Sorry, I haven't done it using anaconda.

**Comment by shoutOutYangJie** [comment]
Hello, @fperazzi  Do you know how to use anaconda (py3.6) to support "t_stab" library?
