### ISSUE TITLE
Any update for DAVIS 2017?

### ISSUE THREAD

**Issue by bhack** [fperazzi/davis#6]

**Comment by fperazzi** [comment]
Yes, I'll release a new version in the upcoming days.

Federico

**Comment by fperazzi** [comment]
There you go: https://github.com/fperazzi/davis-2017

**Comment by bhack** [comment]
Thanks

**Comment by fperazzi** [comment]
No problem, I didn't have time to thoroughly test the code, if you have problem, just open an issue in the repo. Thanks!
