### ISSUE TITLE
Why strip the last frame when doing evaluation?

### ISSUE THREAD

**Issue by Beanocean** [fperazzi/davis#7]
https://github.com/fperazzi/davis/blob/aaee12c9dd83b1709d05c38754c72570283c1c84/python/lib/davis/dataset/loader.py#L206

Why need to strip the last frame when doing the performance evaluation? Just like the above code shows

**Comment by fperazzi** [comment]
The forward optical flow is undefined on the last frame and some of the
approaches that make use of it do not output the segmentation for the last
frame.

**Comment by Beanocean** [comment]
OK, Thanks a lot, @fperazzi
